import type { Metadata } from "next";
import AdminRoute from "@/common/Auth/AdminRoute";
import LogoutButton from "@/common/Auth/components/LogoutButton";
import {handleLogout} from "@/common/Auth/actions";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AdminRoute>
            <div>
                <LogoutButton handleLogout={handleLogout}>
                    Log Out
                </LogoutButton>
            </div>
            {children}
        </AdminRoute>
    );
}
